### ISSUE TITLE
Node-version restrictions added in package.json breaks my build

### ISSUE THREAD

**Issue by random-tech** [Eyevinn/is-drm-supported#5]
We are using Gitlab runners with node 19.7.0 to build our project. Have not had any issues previously, but I see you added in node-version restrictions now that means node 19.7.0 is no longer supported, and this breaks our build.

As a temporary fix I have downgraded the version of is-drm-supported we use to 1.2.1, but it would be nice to be able to use the latest versions.

**Comment by martinstark** [comment]
Thanks for notifying us. I'll patch this, the change was intended to affect developers of the package, not consumers.

**Comment by martinstark** [comment]
Fixed in [1.4.1](https://www.npmjs.com/package/@eyevinn/is-drm-supported/v/1.4.1)
